DLG System is ready for implementation
DrunkReaperMatt/LOG795-A19 pull request #10
Opened 2019-11-09 16:20 UTC by DrunkReaperMatt

Plugin ready to merge

NB.
- **New** Blueprint Class from Rosetta Character
- **New** Game mode Blueprint 
- **New** Added Blueprint properties for dialogue trees files

2019-11-11 01:07 UTC, karakune requested changes

2019-11-11 01:07 UTC, karakune commented on Source/Rosetta/RosettaCharacter.cpp
> +#include "NonPlayerCharacter.h"
est-ce que ce include est nécessaire?

2019-11-11 01:07 UTC, karakune commented on Source/Rosetta/RosettaCharacter.cpp
> +		//StartDialogue(Cast<ANonPlayerCharacter>(InteractableHit)->dialogueData, Cast<ANonPlayerCharacter>(InteractableHit));
À retirer

2019-11-11 01:07 UTC, karakune commented on Source/Rosetta/RosettaCharacter.h
> +	// 	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = DlgData, meta = (AllowPrivateAccess = "true"))
À retirer?

2019-11-11 01:07 UTC, karakune commented on Source/Rosetta/NonPlayerCharacter.h
> +	virtual void Interact()override;
add space after ) for clarity

2019-11-11 01:07 UTC, karakune commented on Source/Rosetta/NonPlayerCharacter.cpp
> +/// Old Code from widget
delete if not-necessary

2019-11-11 01:07 UTC, karakune commented on Source/Rosetta/DialogueWidget.cpp
> +	//	DialogueStep++;
delete if not-necessary

2019-11-11 01:16 UTC, DrunkReaperMatt commented on Source/Rosetta/RosettaCharacter.cpp
> +#include "NonPlayerCharacter.h"
npc.h est superflu

removed

2019-11-11 01:17 UTC, DrunkReaperMatt commented on Source/Rosetta/RosettaCharacter.h
> +	// 	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = DlgData, meta = (AllowPrivateAccess = "true"))
est retirer

2019-11-20 14:01 UTC, karakune approved these changes

2019-11-20 14:01 UTC, karakune commented on Source/Rosetta/DialogueWidget.cpp
> +	Player->widget = this;
renommer widget pour quelque chose de plus explicite

2019-11-20 14:20 UTC, merged